# Use the official Ruby image
FROM ruby:latest

# Set the working directory in the container
WORKDIR /usr/src/ASL_Assignment

# Copy the current directory contents into the container at /usr/src/myapp
COPY . .

# Run Ruby script
CMD [ "ruby", "./hello.rb" ]

