# Use the official PHP image
FROM php:latest

# Set the working directory in the container
WORKDIR /usr/src/ASL_Assignment

# Copy the current directory contents into the container at /usr/src/myapp
COPY . .

# Run PHP script
CMD [ "php", "./hello.php" ]

